version: '3'

services:

  db:
    image: postgres:alpine
    container_name: nextcloud_db
    restart: unless-stopped
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PW}
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    links:
      - db    
    volumes:
      - nextcloud-web:/var/www/html
    environment:
      VIRTUAL_HOST: dav.${NEXTCLOUD_DOMAIN_NAME}
      LETSENCRYPT_HOST: dav.${NEXTCLOUD_DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  nextcloud-web:
  nextcloud-db: