version: '3'

services:
  owncloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - ${NEXTCLOUD_PATH}:/var/www/html
    environment:
      VIRTUAL_HOST: dav.${NEXTCLOUD_DOMAIN_NAME}
      LETSENCRYPT_HOST: dav.${NEXTCLOUD_DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
  default:
    external:
      name: nginx-proxy