version: '3'

services:
  beehive:
    image: fribbledom/beehive
    container_name: beehive
    ports:
      - "8181:8181"
    restart: unless-stopped
    environment:
      CANONICAL_URL: http://beehive.${DOMAIN_NAME}:8181

