version: '3'

services:
  blog:
    container_name: blog
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ${SFTP_VOLUME}:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: ${WEB_DOMAIN_NAME}, www.${WEB_DOMAIN_NAME}, blog.${WEB_DOMAIN_NAME}
      LETSENCRYPT_HOST: ${WEB_DOMAIN_NAME}, www.${WEB_DOMAIN_NAME}, blog.${WEB_DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  sftp:
    container_name: blog-sftp
    image: atmoz/sftp:alpine
    restart: unless-stopped
    volumes:
      - ${SFTP_VOLUME}:/home/blog/upload
    ports:
      - "2222:22"
    command: blog:${SFTP_PW}:${UID}:${GID}:upload

networks:
  default:
    external:
      name: nginx-proxy
