version: '3'

services:
  blog:
    container_name: blog
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ${WEB_FILE_PATH}:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: ${WEB_DOMAIN_NAME}, www.${WEB_DOMAIN_NAME}, blog.${WEB_DOMAIN_NAME}
      LETSENCRYPT_HOST: ${WEB_DOMAIN_NAME}, www.${WEB_DOMAIN_NAME}, blog.${WEB_DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}@${WEB_DOMAIN_NAME}

networks:
  default:
    external:
      name: webproxy