shadowsocks:
  image: shadowsocks-libev
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=rc4-md5
    - PASSWORD=foobar
    - SERVER_ADDR="["[::0]","0.0.0.0"]"
  restart: unless-stopped