shadowsocks:
  image: shadowsocks-libev
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=${SS_METHOD}
    - PASSWORD=${SS_PW}
    - ARGS="-s ::"
  restart: unless-stopped